#!/bin/bash
set -euo pipefail

DOCKER_USER="hkjn"
DOCKER_IMAGE="workspace"
ARCH="$(uname -m)"
BUILD_DIR="$(mktemp -d)"
ARCHBASE="hkjn/arch:$ARCH"
ALPINEBASE="hkjn/alpine:$ARCH"
VERSION=1.0.2
TAG="$DOCKER_USER/$DOCKER_IMAGE:$ARCH"
ARUNABASE="hkjn/workspace:$ARCH-arch-$VERSION"
NO_PUSH=${NO_PUSH:-""}

mkdir -p $BUILD_DIR/aruna
sed "s|ARG_FROM|${ARCHBASE}|g" Dockerfile.arch > $BUILD_DIR/Dockerfile.arch
sed "s|ARG_FROM|${ALPINEBASE}|g" Dockerfile.alpine > $BUILD_DIR/Dockerfile.alpine
sed "s|ARG_FROM|${ARUNABASE}|g" aruna/Dockerfile.in > $BUILD_DIR/aruna/Dockerfile
cp -vr .bash_profile .emacs* $BUILD_DIR/
cp -vr aruna $BUILD_DIR/
echo "Building $TAG-arch in $BUILD_DIR.."
cd $BUILD_DIR
docker build -t $TAG-arch-$VERSION -f Dockerfile.arch .
echo "Building $TAG-alpine in $BUILD_DIR.."
docker build -t $TAG-alpine-$VERSION -f Dockerfile.alpine .
echo "Building $TAG-aruna-$VERSION in $BUILD_DIR.."
docker build -t $TAG-aruna-$VERSION aruna/
[[ "$NO_PUSH" ]] || {
  docker push $TAG-arch-$VERSION
  docker push $TAG-alpine-$VERSION
  docker push $TAG-aruna-$VERSION
}
