#!/bin/bash
#
# This is the entrypoint script for hkjn/workspace.
#

ssh-keygen -b 4096 -t rsa -f /etc/ssh/ssh_host_rsa_key -N ''

ssh-keygen -b 4096 -t rsa -f /home/user/.ssh/id_rsa -N ''

cat /home/user/.ssh/id_rsa.pub >> .ssh/authorized_keys
chmod 400 /home/user/.ssh/authorized_keys

cat /home/user/.ssh/id_rsa.pub >> .ssh/authorized_keys
chmod 400 /home/user/.ssh/authorized_keys

chown -R user:user /home/user

# TODO: Since sshd exits when connection ends in foreground mode, we
# should run it with supervisord if we want the container to be
# persistent: https://docs.docker.com/engine/admin/using_supervisord/
# exec /usr/sbin/sshd -D

